/*
==================================================================================================================================================================
Update-WE_Tables.sql

.Description
	Copy/Paste the resulting statements from the Get-WE_UpdateTableStatements.sql stored proceedure into the BEGIN/COMMIT TRANSACTION block of this script.
	This will update all rows of the specified column, in any table with that column name. For example, every database table that has a 'Branch' column will
	have '902' as the new value for that column. To further refine the generated UPDATE statments, edit the WHERE block of the script.

.Examples
	-EXEC Update_WE_Tables 'Column1', 'NewValue'

.Notes
	To-do:
		-Allow for database_name parameter
		-Separate into two different stored proceedures (1) generate UPDATE statements (2) while loop against UPDATE statements with transaction rolback.
	Tested
==================================================================================================================================================================
*/

BEGIN TRY

	BEGIN TRANSACTION UPDATE_TABLES

		/*
		Copy/Paste the UPDATE statements generated by the Update_WE_Tables proceedure
		Example: UPDATE POSPrinters SET NoLock=1;
		*/

	COMMIT TRANSACTION UPDATE_TABLES

	PRINT 'All tables have been updated.';

END TRY

BEGIN CATCH

IF (@@TRANCOUNT > 0)

BEGIN

	ROLLBACK TRANSACTION UPDATE_TABLES;

	PRINT 'Error detected, all changes reversed';

END

	SELECT
	ERROR_NUMBER() AS ErrorNumber,
	ERROR_SEVERITY() AS ErrorSeverity,
	ERROR_STATE() AS ErrorState,
	ERROR_PROCEDURE() AS ErrorProcedure,
	ERROR_LINE() AS ErrorLine,
	ERROR_MESSAGE() AS ErrorMessage;

END CATCH